<p style="text-align:center; font-weight:bolder;"> Nhà tài trợ</p>
<div style="margin-left:2em;">
<p style="text-align: center;"><strong><span style="font-size: 44.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">Black and White</span></strong></p>
<center><img src="../img/ntt1.png" alt=""></center>
<p><span style="font-family: 'Times New Roman','serif';">&nbsp;</span></p>
<p style="text-align: center;"><strong><span style="font-size: 20.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">DỰ &Aacute;N X&Acirc;Y DỰNG THƯ VIỆN ĐIỆN TỬ D&Agrave;NH CHO SINH VI&Ecirc;N KHIẾM THỊ</span></strong></p>
<p style="text-align: center;"><strong><span style="font-size: 26.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">HỒ SƠ MỜI T&Agrave;I TRỢ</span></strong></p>
<center><img src="../img/ntt2.png" alt=""></center>
<p style="text-align: center;"><strong><span style="font-size: 26.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">&nbsp;</span></strong></p>
<p style="text-align: center;"><span style="font-size: 16.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">&nbsp;</span><span style="font-family: 'Times New Roman', serif; font-size: 16pt;">Hồ Ch&iacute; Minh, ng&agrave;y 10 th&aacute;ng 7 năm 2017</span></p>
<p style="text-align: center; tab-stops: 14.2pt right dotted 6.3in;"><strong><span style="font-size: 22.0pt; line-height: 115%; font-family: 'Constantia','serif'; color: #c00000;">THƯ NGỎ</span></strong></p>
<p style="margin-left: 28.35pt; text-indent: 7.1pt; tab-stops: 14.2pt right dotted 6.3in;"><em><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">K&iacute;nh thưa qu&yacute; c&ocirc;ng ty</span></em></p>
<p style="text-align: justify; text-indent: 35.45pt; tab-stops: right dotted 6.3in;"><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">Black and White l&agrave; một nh&oacute;m c&aacute;c bạn trẻ khuyết tật đang sinh sống, học tập tại th&agrave;nh phố Hồ Ch&iacute; Minh. Nh&oacute;m ch&uacute;ng t&ocirc;i th&agrave;nh lập với sứ mệnh gi&uacute;p đỡ c&aacute;c bạn sinh vi&ecirc;n khiếm thị đang gặp kh&oacute; khăn trong việc học tập v&agrave; t&igrave;m kiếm t&agrave;i liệu ph&ugrave; hợp với chuy&ecirc;n ng&agrave;nh. C&aacute;c bạn ấy kh&ocirc;ng thể học tốt, kh&ocirc;ng thể chủ động trong việc học tập v&agrave; nghi&ecirc;n cứu, kh&ocirc;ng thể mở rộng được vốn tri thức v&agrave; hệ quả đi c&ugrave;ng l&agrave; kết quả của c&aacute;c bạn ấy kh&ocirc;ng tốt, kh&ocirc;ng thể theo kịp được với những người b&igrave;nh thường, cơ hội nghề nghiệp v&agrave; ph&aacute;t triển của c&aacute;c bạn ấy cũng &iacute;t hơn. S&aacute;ch đối với c&aacute;c bạn ấy v&ocirc; c&ugrave;ng quan trọng tuy nhi&ecirc;n nguồn cung cấp ch&iacute;nh thức th&igrave; gần như l&agrave; kh&ocirc;ng c&oacute;.</span></p>
<p style="text-align: justify; text-indent: 35.45pt; tab-stops: right dotted 6.3in;"><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">Để giải quyết c&aacute;c vấn đề m&agrave; c&aacute;c bạn sinh vi&ecirc;n khiếm thị gặp phải, nh&oacute;m Black and White x&acirc;y dựng một trang web Thư Viện Điện Tử l&agrave; một k&ecirc;nh cung cấp t&agrave;i liệu cho c&aacute;c bạn ấy. B&ecirc;n cạnh đ&oacute;, Black and White k&ecirc;u gọi cộng đồng hỗ trợ nhằm ph&aacute;t triển dự &aacute;n, đồng h&agrave;nh c&ugrave;ng Black and White trong sứ mệnh trao cơ hội v&agrave; mở rộng tương lai cho c&aacute;c bạn sinh vi&ecirc;n khiếm thị.</span></p>
<p style="text-align: justify; text-indent: 35.45pt; tab-stops: right dotted 6.3in;"><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">Bất kỳ một doanh nghiệp c&oacute; định hướng ph&aacute;t triển bền vững n&agrave;o cũng lu&ocirc;n mang theo m&igrave;nh lời nhắn nhủ về tr&aacute;ch nhiệm cộng đồng. Trở th&agrave;nh nh&agrave; t&agrave;i trợ của dự &aacute;n Black and White, Qu&yacute; c&ocirc;ng ty kh&ocirc;ng chỉ trao cơ hội cho c&aacute;c bạn sinh vi&ecirc;n khiếm thị. Hơn nữa, Qu&yacute; C&ocirc;ng Ty cũng tham gia n&acirc;ng cao nhận thức về tr&aacute;ch nhiệm cộng đồng trong x&atilde; hội Việt Nam. Nếu mỗi người chung tay g&oacute;p một phần c&ocirc;ng sức v&agrave; quan t&acirc;m hơn đến những người khuyết tật chịu nhiều thiệt th&ograve;i, th&igrave; ch&uacute;ng ta đang x&acirc;y dựng một cộng đồng vững chắc v&agrave; ủ ấp nhiều t&igrave;nh cảm tr&acirc;n qu&yacute; trong tương lai. </span></p>
<p style="text-align: justify; text-indent: 35.45pt; tab-stops: right dotted 6.3in;"><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">Ch&uacute;ng t&ocirc;i hy vọng Qu&yacute; C&ocirc;ng Ty sẽ d&agrave;nh &iacute;t thời giờ qu&yacute; gi&aacute; trong ng&agrave;y l&agrave;m việc bộn bề của m&igrave;nh, lưu ch&uacute;t t&acirc;m v&agrave; l&ograve;ng đến bộ hồ sơ n&agrave;y. Biết đ&acirc;u từ đ&oacute;, một cuộc đời ngo&agrave;i kia sẽ được trao một cơ hội tuyệt vời...</span></p>
<p style="text-align: justify; text-indent: 35.45pt; tab-stops: 14.2pt right dotted 6.3in;"><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">Tr&acirc;n trọng tri &acirc;n!</span></p>
<p style="text-align: right; tab-stops: 14.2pt right dotted 6.3in;"><span style="font-size: 16.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">Nguyễn Ngọc Hiệp - Trưởng nh&oacute;m Black and White</span></p>
<p><span style="font-size: 11.0pt; line-height: 115%; font-family: 'Calibri','sans-serif';"><br style="page-break-before: always;" /> </span></p>
<p>&nbsp;</p>
<p style="text-align: center; tab-stops: 14.2pt right dotted 6.3in;"><strong><span style="font-size: 22.0pt; line-height: 115%; font-family: 'Constantia','serif'; color: #c00000;">M&Ocirc; TẢ DỰ &Aacute;N</span></strong></p>
<p style="text-align: justify; text-indent: 35.45pt; tab-stops: right dotted 6.3in;"><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">Black and White l&agrave; một dự &aacute;n thư viện điện tử d&agrave;nh cho c&aacute;c bạn sinh vi&ecirc;n khiếm thị ở TP.HCM, với sự triển khai thực hiện trực tiếp của nh&oacute;m sinh vi&ecirc;n khuyết tật Black and White th&ocirc;ng qua cuộc thi UpShift do Unicef v&agrave; VYE hướng dẫn v&agrave; hỗ trợ.</span></p>
<p style="text-align: justify; text-indent: 35.45pt; tab-stops: right dotted 6.3in;"><strong><span style="font-size: 16.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">Mục ti&ecirc;u dự &aacute;n:</span></strong><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';"> X&acirc;y dựng Black and White th&agrave;nh một địa chỉ t&igrave;m kiếm th&ocirc;ng tin, t&agrave;i liệu quen thuộc của tất cả sinh vi&ecirc;n khiếm thị đang học ở c&aacute;c trường cao đẳng, đại học tr&ecirc;n địa b&agrave;n TP.HCM. Với giao diện đơn giản, ho&agrave;n to&agrave;n miễn ph&iacute; v&agrave; nguồn t&agrave;i liệu phong ph&uacute;, ph&acirc;n loại r&otilde; r&agrave;ng. Ch&uacute;ng t&ocirc;i mong muốn mang tới bạn kho tri thức v&ocirc; tận của nh&acirc;n loại một c&aacute;ch dễ d&agrave;ng nhất.</span></p>
<p style="text-align: justify; text-indent: 35.45pt;"><strong><span style="font-size: 16.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">&Yacute; nghĩa:</span></strong><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';"> Black and White l&agrave; hai ranh giới giữa trắng v&agrave; đen, giữa thế giới của người khiếm thị v&agrave; thế giới của người b&igrave;nh thường, l&agrave; sự tối tăm của ngu dốt v&agrave; sự th&ocirc;ng tuệ do tri thức chiếu rọi... Hai thế giới kh&aacute;c nhau, hai mảnh đời tr&aacute;i ngược nhưng tri thức sẽ k&eacute;o họ tới gần nhau hơn v&agrave; xo&aacute; dần đi khoảng c&aacute;ch ấy. M&agrave;u trắng của giấy v&agrave; m&agrave;u đen của mực ho&agrave; quyện v&agrave;o nhau, tạo n&ecirc;n những trang giấy mang v&ocirc; v&agrave;n kiến thức lo&agrave;i người, mang theo niềm tin, ước mơ của người khiếm thị được ho&agrave; nhập với x&atilde; hội.</span></p>
<center><img src="../img/ntt3.png" alt=""></center><br>
<p style="text-align: center;"><strong><span style="font-size: 22.0pt; line-height: 115%; font-family: 'Constantia','serif'; color: #c00000;">QUYỀN LỢI NH&Agrave; T&Agrave;I TRỢ</span></strong></p>
<ol>
<li style="text-indent: -.25in;"><strong><span style="font-size: 18.0pt; line-height: 115%; font-family: 'Monotype Corsiva'; color: #7030a0;">Ai c&oacute; th</span></strong><strong><span style="font-size: 18.0pt; line-height: 115%; font-family: 'Times New Roman','serif'; color: #7030a0;">ể</span></strong><strong><span style="font-size: 18.0pt; line-height: 115%; font-family: 'Monotype Corsiva'; color: #7030a0;"> l&agrave; nh&agrave; t&agrave;i tr</span></strong><strong><span style="font-size: 18.0pt; line-height: 115%; font-family: 'Times New Roman','serif'; color: #7030a0;">ợ</span></strong><strong><span style="font-size: 18.0pt; line-height: 115%; font-family: 'Monotype Corsiva'; color: #7030a0;">? </span></strong></li>
</ol>
<p style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">Tất cả c&aacute;c tổ chức, c&ocirc;ng ty, c&aacute; nh&acirc;n trong v&agrave; ngo&agrave;i nước c&oacute; giấy ph&eacute;p kinh doanh theo luật ph&aacute;p Việt Nam v&agrave; c&oacute; nguồn t&agrave;i ch&iacute;nh ph&ugrave; hợp để t&agrave;i trợ cho Dự &aacute;n Black and White.</span></p>
<ol start="2">
<li style="text-align: justify; text-indent: -.25in;"><strong><span style="font-size: 18.0pt; line-height: 115%; font-family: 'Monotype Corsiva'; color: #7030a0;">L&agrave;m th</span></strong><strong><span style="font-size: 18.0pt; line-height: 115%; font-family: 'Times New Roman','serif'; color: #7030a0;">ế</span></strong><strong><span style="font-size: 18.0pt; line-height: 115%; font-family: 'Monotype Corsiva'; color: #7030a0;"> n&agrave;o đ</span></strong><strong><span style="font-size: 18.0pt; line-height: 115%; font-family: 'Times New Roman','serif'; color: #7030a0;">ể</span></strong><strong><span style="font-size: 18.0pt; line-height: 115%; font-family: 'Monotype Corsiva'; color: #7030a0;"> t&agrave;i tr</span></strong><strong><span style="font-size: 18.0pt; line-height: 115%; font-family: 'Times New Roman','serif'; color: #7030a0;">ợ</span></strong><strong><span style="font-size: 18.0pt; line-height: 115%; font-family: 'Monotype Corsiva'; color: #7030a0;">?</span></strong></li>
<li style="text-align: justify; text-indent: -.25in;"><strong><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">Bằng tiền: VND</span></strong></li>
</ol>
<p style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">Nh&agrave; t&agrave;i trợ chuyển giao tiền mặt cho đại diện Black and White, hoặc chuyển tiền v&agrave;o t&agrave;i khoản ng&acirc;n h&agrave;ng dưới đ&acirc;y:</span></p>
<p style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">- Ng&acirc;n h&agrave;ng: Techcombank</span></p>
<p style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">- T&ecirc;n t&agrave;i khoản: Nguyễn Ngọc Hiệp</span></p>
<p style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">- VND Số t&agrave;i khoản: 19028079902015</span></p>
<p style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">- Chi nh&aacute;nh: Nguyễn Ch&iacute; Thanh, Quận 5</span></p>
<p style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">(Xin ghi r&otilde; &ldquo;Ho tro du an Black and White&rdquo; khi chuyển khoản)</span></p>
<p style="margin-left: 42.55pt; text-align: justify;"><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">&nbsp;</span></p>
<ol>
<li style="text-align: justify; text-indent: -.25in;"><strong><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">Bằng sản phẩm v&agrave; dịch vụ:</span></strong> <span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">li&ecirc;n quan đến dự &aacute;n như địa điểm đặt trụ sở, t&agrave;i liệu, s&aacute;ch vở, văn ph&ograve;ng phẩm, quảng c&aacute;o, học bổng, việc l&agrave;m, v.v...</span></li>
</ol>
<p style="margin-left: 35.45pt; text-align: justify;"><span style="font-size: 14.0pt; line-height: 115%; font-family: 'Times New Roman','serif';">C&aacute;c nh&agrave; hảo t&acirc;m, nh&agrave; t&agrave;i trợ, đối t&aacute;c khi gi&uacute;p đỡ dự &aacute;n, sẽ mang lại nguồn động vi&ecirc;n to lớn cho cộng đồng người khiếm thị n&oacute;i chung, v&agrave; cộng đồng học sinh sinh vi&ecirc;n khiếm thị n&oacute;i ri&ecirc;ng... Hơn nữa, ch&uacute;ng t&ocirc;i tr&acirc;n trọng h&agrave;nh động hỗ trợ của qu&yacute; vị khi chung tay xo&aacute; bỏ khoảng c&aacute;ch của những mảnh đời kh&oacute; khăn với cộng đồng. Ch&uacute;ng t&ocirc;i vinh hạnh lưu t&ecirc;n qu&yacute; vị v&agrave;o danh s&aacute;ch c&aacute;c nh&agrave; t&agrave;i trợ tr&ecirc;n trang thư viện của ch&uacute;ng t&ocirc;i.</span></p>
</div>
